# Configuration de la langue
language: "en"  # Options: fr, en, es, de, it


banned-words:
  - fuck
  - shit

# Emojis configurables
emojis:
  ":smile:": "ğŸ˜Š"
  ":sad:": "ğŸ˜¢"
  ":heart:": "â¤ï¸"
  ":star:": "â­"
  # Ajoute d'autres emojis ici
